---
# tasks file

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    update_cache: yes
    state: latest    

- name: Install the package "git"
  ansible.builtin.apt:
    name: git
    state: latest