---
- name: Configurar servidor 
  hosts: node01
  remote_user: vagrant  

  vars:
    dbname: db01
    dbusername: root
    dbpassword: mypassword

  tasks:
    - name: Configurar hosts 
      become: yes
      ansible.builtin.lineinfile: 
        path: /etc/hosts
        create: yes
        # line: "{{item.key}} {{item.value}}"
        line: "{{item}}"
      with_lines:
        - cat "/vagrant/playbooks/hosts.txt"        

  become: yes      
  roles:
    - ubuntu-setup

